2014-01-06T13:25:29-05:00 ERR (3): SELECT `pm1`.`role_nombre` AS `role`, `pm2`.`role_nombre` AS `extend` FROM `role` AS `pm1`
 LEFT JOIN `role` AS `pm2` ON pm1.role_extends=pm2.role_id WHERE (pm1.role_activo=1) ORDER BY `pm1`.`role_id` ASC
2014-01-06T13:28:53-05:00 ERR (3): SELECT `pm1`.`role_nombre` AS `role`, `pm2`.`role_nombre` AS `extend` FROM `role` AS `pm1`
 LEFT JOIN `role` AS `pm2` ON pm1.role_extends=pm2.role_id WHERE (pm1.role_activo=1) ORDER BY `pm1`.`role_id` ASC
2014-01-06T13:28:56-05:00 ERR (3): SELECT `pm1`.`role_nombre` AS `role`, `pm2`.`role_nombre` AS `extend` FROM `role` AS `pm1`
 LEFT JOIN `role` AS `pm2` ON pm1.role_extends=pm2.role_id WHERE (pm1.role_activo=1) ORDER BY `pm1`.`role_id` ASC
2014-01-06T13:33:07-05:00 ERR (3): SELECT `pm1`.`role_nombre` AS `role`, `pm2`.`role_nombre` AS `extend` FROM `role` AS `pm1`
 LEFT JOIN `role` AS `pm2` ON pm1.role_extends=pm2.role_id WHERE (pm1.role_activo=1) ORDER BY `pm1`.`role_id` ASC
2014-01-06T13:37:32-05:00 ERR (3): SELECT `pm1`.`role_nombre` AS `role`, `pm2`.`role_nombre` AS `extend` FROM `role` AS `pm1`
 LEFT JOIN `role` AS `pm2` ON pm1.role_extends=pm2.role_id WHERE (pm1.role_activo=1) ORDER BY `pm1`.`role_id` ASC
2014-01-06T13:37:36-05:00 ERR (3): SELECT `pm1`.`role_nombre` AS `role`, `pm2`.`role_nombre` AS `extend` FROM `role` AS `pm1`
 LEFT JOIN `role` AS `pm2` ON pm1.role_extends=pm2.role_id WHERE (pm1.role_activo=1) ORDER BY `pm1`.`role_id` ASC
2014-01-06T13:37:45-05:00 ERR (3): SELECT `pm1`.`role_nombre` AS `role`, `pm2`.`role_nombre` AS `extend` FROM `role` AS `pm1`
 LEFT JOIN `role` AS `pm2` ON pm1.role_extends=pm2.role_id WHERE (pm1.role_activo=1) ORDER BY `pm1`.`role_id` ASC
2014-01-06T13:38:12-05:00 ERR (3): SELECT `pm1`.`role_nombre` AS `role`, `pm2`.`role_nombre` AS `extend` FROM `role` AS `pm1`
 LEFT JOIN `role` AS `pm2` ON pm1.role_extends=pm2.role_id WHERE (pm1.role_activo=1) ORDER BY `pm1`.`role_id` ASC
2014-01-06T13:38:33-05:00 ERR (3): SELECT `pm1`.`role_nombre` AS `role`, `pm2`.`role_nombre` AS `extend` FROM `role` AS `pm1`
 LEFT JOIN `role` AS `pm2` ON pm1.role_extends=pm2.role_id WHERE (pm1.role_activo=1) ORDER BY `pm1`.`role_id` ASC
2014-01-06T13:40:37-05:00 ERR (3): SELECT `pm1`.`role_nombre` AS `role`, `pm2`.`role_nombre` AS `extend` FROM `role` AS `pm1`
 LEFT JOIN `role` AS `pm2` ON pm1.role_extends=pm2.role_id WHERE (pm1.role_activo=1) ORDER BY `pm1`.`role_id` ASC
2014-01-06T14:01:24-05:00 ERR (3): SELECT `pm1`.`role_nombre` AS `role`, `pm2`.`role_nombre` AS `extend` FROM `role` AS `pm1`
 LEFT JOIN `role` AS `pm2` ON pm1.role_extends=pm2.role_id WHERE (pm1.role_activo=1) ORDER BY `pm1`.`role_id` ASC
2014-01-08T10:59:50-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'dgamarra') AND (usuario_id <> 'dgamarra')
2014-01-08T10:59:52-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'dgamarra') AND (usuario_id <> 'dgamarra')
2014-01-08T10:59:57-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'dgamarra') AND (usuario_id <> 'dgamarra')
2014-01-08T11:00:01-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'dgamarra') AND (usuario_id <> 'dgamarra')
2014-01-08T11:00:02-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'dgamarra') AND (usuario_id <> 'dgamarra')
2014-01-08T11:00:03-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'dgamarra') AND (usuario_id <> 'dgamarra')
2014-01-08T11:00:05-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'dgamarra') AND (usuario_id <> 'dgamarra')
2014-01-08T11:00:06-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'dgamarra') AND (usuario_id <> 'dgamarra')
2014-01-08T11:00:12-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'dgamarra') AND (usuario_id <> 'dgamarra')
2014-01-08T11:10:42-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'user1') AND (usuario_id <> 'user1')
2014-01-08T13:48:48-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'usuario_activo' in 'field list'' in /var/www/legal/library/Zend/Db/Statement/Mysqli.php:77
Stack trace:
#0 /var/www/legal/library/Zend/Db/Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('UPDATE `usuario...')
#1 /var/www/legal/library/Zend/Db/Adapter/Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'UPDATE `usuario...')
#2 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('UPDATE `usuario...')
#3 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(635): Zend_Db_Adapter_Abstract->query('UPDATE `usuario...', Array)
#4 /var/www/legal/library/Zend/Db/Table/Abstract.php(1133): Zend_Db_Adapter_Abstract->update('usuario', Array, 'usuario_id =14')
#5 /var/www/legal/library/Core/Db/Table.php(20): Zend_Db_Table_Abstract->update(Array, 'usuario_id =14')
#6 /var/www/legal/application/models/Usuario.php(124): Core_Db_Table->update(Array, 'usuario_id =14')
#7 /var/www/legal/application/entitys/Usuario.php(153): Application_Model_Usuario->update(14, Array)
#8 /var/www/legal/application/modules/administracion/controllers/UsuarioController.php(133): Application_Entity_Usuario::activar(14, 0)
#9 /var/www/legal/library/Zend/Controller/Action.php(516): Administracion_UsuarioController->activarAction()
#10 /var/www/legal/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('activarAction')
#11 /var/www/legal/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /var/www/legal/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 /var/www/legal/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 /var/www/legal/public/index.php(27): Zend_Application->run()
#15 {main}
2014-01-08T13:48:50-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'usuario_activo' in 'field list'' in /var/www/legal/library/Zend/Db/Statement/Mysqli.php:77
Stack trace:
#0 /var/www/legal/library/Zend/Db/Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('UPDATE `usuario...')
#1 /var/www/legal/library/Zend/Db/Adapter/Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'UPDATE `usuario...')
#2 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('UPDATE `usuario...')
#3 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(635): Zend_Db_Adapter_Abstract->query('UPDATE `usuario...', Array)
#4 /var/www/legal/library/Zend/Db/Table/Abstract.php(1133): Zend_Db_Adapter_Abstract->update('usuario', Array, 'usuario_id =14')
#5 /var/www/legal/library/Core/Db/Table.php(20): Zend_Db_Table_Abstract->update(Array, 'usuario_id =14')
#6 /var/www/legal/application/models/Usuario.php(124): Core_Db_Table->update(Array, 'usuario_id =14')
#7 /var/www/legal/application/entitys/Usuario.php(153): Application_Model_Usuario->update(14, Array)
#8 /var/www/legal/application/modules/administracion/controllers/UsuarioController.php(133): Application_Entity_Usuario::activar(14, 0)
#9 /var/www/legal/library/Zend/Controller/Action.php(516): Administracion_UsuarioController->activarAction()
#10 /var/www/legal/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('activarAction')
#11 /var/www/legal/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /var/www/legal/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 /var/www/legal/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 /var/www/legal/public/index.php(27): Zend_Application->run()
#15 {main}
2014-01-08T13:48:51-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'usuario_activo' in 'field list'' in /var/www/legal/library/Zend/Db/Statement/Mysqli.php:77
Stack trace:
#0 /var/www/legal/library/Zend/Db/Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('UPDATE `usuario...')
#1 /var/www/legal/library/Zend/Db/Adapter/Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'UPDATE `usuario...')
#2 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('UPDATE `usuario...')
#3 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(635): Zend_Db_Adapter_Abstract->query('UPDATE `usuario...', Array)
#4 /var/www/legal/library/Zend/Db/Table/Abstract.php(1133): Zend_Db_Adapter_Abstract->update('usuario', Array, 'usuario_id =14')
#5 /var/www/legal/library/Core/Db/Table.php(20): Zend_Db_Table_Abstract->update(Array, 'usuario_id =14')
#6 /var/www/legal/application/models/Usuario.php(124): Core_Db_Table->update(Array, 'usuario_id =14')
#7 /var/www/legal/application/entitys/Usuario.php(153): Application_Model_Usuario->update(14, Array)
#8 /var/www/legal/application/modules/administracion/controllers/UsuarioController.php(133): Application_Entity_Usuario::activar(14, 0)
#9 /var/www/legal/library/Zend/Controller/Action.php(516): Administracion_UsuarioController->activarAction()
#10 /var/www/legal/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('activarAction')
#11 /var/www/legal/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /var/www/legal/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 /var/www/legal/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 /var/www/legal/public/index.php(27): Zend_Application->run()
#15 {main}
2014-01-08T15:56:07-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'sede_especialidad' in 'field list'' in /var/www/legal/library/Zend/Db/Statement/Mysqli.php:77
Stack trace:
#0 /var/www/legal/library/Zend/Db/Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('INSERT INTO `se...')
#1 /var/www/legal/library/Zend/Db/Adapter/Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'INSERT INTO `se...')
#2 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('INSERT INTO `se...')
#3 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `se...', Array)
#4 /var/www/legal/library/Zend/Db/Table/Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('sede', Array)
#5 /var/www/legal/library/Core/Db/Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#6 /var/www/legal/application/models/Sede.php(37): Core_Db_Table->insert(Array)
#7 /var/www/legal/application/entitys/Sede.php(37): Application_Model_Sede->insert(Array)
#8 /var/www/legal/application/modules/administracion/controllers/SedeController.php(23): Application_Entity_Sede->insert()
#9 /var/www/legal/library/Zend/Controller/Action.php(516): Administracion_SedeController->nuevoAction()
#10 /var/www/legal/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#11 /var/www/legal/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /var/www/legal/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 /var/www/legal/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 /var/www/legal/public/index.php(27): Zend_Application->run()
#15 {main}
2014-01-08T15:57:19-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'sede_especialidad' in 'field list'' in /var/www/legal/library/Zend/Db/Statement/Mysqli.php:77
Stack trace:
#0 /var/www/legal/library/Zend/Db/Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('INSERT INTO `se...')
#1 /var/www/legal/library/Zend/Db/Adapter/Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'INSERT INTO `se...')
#2 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('INSERT INTO `se...')
#3 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `se...', Array)
#4 /var/www/legal/library/Zend/Db/Table/Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('sede', Array)
#5 /var/www/legal/library/Core/Db/Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#6 /var/www/legal/application/models/Sede.php(37): Core_Db_Table->insert(Array)
#7 /var/www/legal/application/entitys/Sede.php(37): Application_Model_Sede->insert(Array)
#8 /var/www/legal/application/modules/administracion/controllers/SedeController.php(23): Application_Entity_Sede->insert()
#9 /var/www/legal/library/Zend/Controller/Action.php(516): Administracion_SedeController->nuevoAction()
#10 /var/www/legal/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#11 /var/www/legal/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /var/www/legal/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 /var/www/legal/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 /var/www/legal/public/index.php(27): Zend_Application->run()
#15 {main}
2014-01-08T15:57:35-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'sede_especialidad' in 'field list'' in /var/www/legal/library/Zend/Db/Statement/Mysqli.php:77
Stack trace:
#0 /var/www/legal/library/Zend/Db/Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('INSERT INTO `se...')
#1 /var/www/legal/library/Zend/Db/Adapter/Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'INSERT INTO `se...')
#2 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('INSERT INTO `se...')
#3 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `se...', Array)
#4 /var/www/legal/library/Zend/Db/Table/Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('sede', Array)
#5 /var/www/legal/library/Core/Db/Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#6 /var/www/legal/application/models/Sede.php(37): Core_Db_Table->insert(Array)
#7 /var/www/legal/application/entitys/Sede.php(37): Application_Model_Sede->insert(Array)
#8 /var/www/legal/application/modules/administracion/controllers/SedeController.php(23): Application_Entity_Sede->insert()
#9 /var/www/legal/library/Zend/Controller/Action.php(516): Administracion_SedeController->nuevoAction()
#10 /var/www/legal/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#11 /var/www/legal/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /var/www/legal/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 /var/www/legal/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 /var/www/legal/public/index.php(27): Zend_Application->run()
#15 {main}
2014-01-08T16:00:04-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'sede_especialidad' in 'field list'' in /var/www/legal/library/Zend/Db/Statement/Mysqli.php:77
Stack trace:
#0 /var/www/legal/library/Zend/Db/Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('INSERT INTO `se...')
#1 /var/www/legal/library/Zend/Db/Adapter/Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'INSERT INTO `se...')
#2 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('INSERT INTO `se...')
#3 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `se...', Array)
#4 /var/www/legal/library/Zend/Db/Table/Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('sede', Array)
#5 /var/www/legal/library/Core/Db/Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#6 /var/www/legal/application/models/Sede.php(37): Core_Db_Table->insert(Array)
#7 /var/www/legal/application/entitys/Sede.php(37): Application_Model_Sede->insert(Array)
#8 /var/www/legal/application/modules/administracion/controllers/SedeController.php(23): Application_Entity_Sede->insert()
#9 /var/www/legal/library/Zend/Controller/Action.php(516): Administracion_SedeController->nuevoAction()
#10 /var/www/legal/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#11 /var/www/legal/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /var/www/legal/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 /var/www/legal/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 /var/www/legal/public/index.php(27): Zend_Application->run()
#15 {main}
2014-01-08T17:34:48-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Cannot add or update a child row: a foreign key constraint fails (`devlegal`.`juzgado`, CONSTRAINT `fk_juzgado_distrito_judicial1` FOREIGN KEY (`distrito_judicial_id`) REFERENCES `distrito_judicial` (`distrito_judicial_id`) ON DELETE NO ACTION ON UPDATE NO A)' in /var/www/legal/library/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /var/www/legal/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `ju...', Array)
#3 /var/www/legal/library/Zend/Db/Table/Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('juzgado', Array)
#4 /var/www/legal/library/Core/Db/Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#5 /var/www/legal/application/models/Juzgado.php(37): Core_Db_Table->insert(Array)
#6 /var/www/legal/application/entitys/Juzgado.php(45): Application_Model_Juzgado->insert(Array)
#7 /var/www/legal/application/modules/administracion/controllers/JuzgadoController.php(22): Application_Entity_Juzgado->insert()
#8 /var/www/legal/library/Zend/Controller/Action.php(516): Administracion_JuzgadoController->nuevoAction()
#9 /var/www/legal/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#10 /var/www/legal/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/legal/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/legal/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/legal/public/index.php(27): Zend_Application->run()
#14 {main}
2014-01-08T17:38:12-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Cannot add or update a child row: a foreign key constraint fails (`devlegal`.`juzgado`, CONSTRAINT `fk_juzgado_distrito_judicial1` FOREIGN KEY (`distrito_judicial_id`) REFERENCES `distrito_judicial` (`distrito_judicial_id`) ON DELETE NO ACTION ON UPDATE NO A)' in /var/www/legal/library/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /var/www/legal/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `ju...', Array)
#3 /var/www/legal/library/Zend/Db/Table/Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('juzgado', Array)
#4 /var/www/legal/library/Core/Db/Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#5 /var/www/legal/application/models/Juzgado.php(37): Core_Db_Table->insert(Array)
#6 /var/www/legal/application/entitys/Juzgado.php(45): Application_Model_Juzgado->insert(Array)
#7 /var/www/legal/application/modules/administracion/controllers/JuzgadoController.php(22): Application_Entity_Juzgado->insert()
#8 /var/www/legal/library/Zend/Controller/Action.php(516): Administracion_JuzgadoController->nuevoAction()
#9 /var/www/legal/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#10 /var/www/legal/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/legal/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/legal/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/legal/public/index.php(27): Zend_Application->run()
#14 {main}
2014-01-08T17:49:48-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Cannot add or update a child row: a foreign key constraint fails (`devlegal`.`juzgado`, CONSTRAINT `fk_juzgado_distrito_judicial1` FOREIGN KEY (`distrito_judicial_id`) REFERENCES `distrito_judicial` (`distrito_judicial_id`) ON DELETE NO ACTION ON UPDATE NO A)' in /var/www/legal/library/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /var/www/legal/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `ju...', Array)
#3 /var/www/legal/library/Zend/Db/Table/Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('juzgado', Array)
#4 /var/www/legal/library/Core/Db/Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#5 /var/www/legal/application/models/Juzgado.php(37): Core_Db_Table->insert(Array)
#6 /var/www/legal/application/entitys/Juzgado.php(45): Application_Model_Juzgado->insert(Array)
#7 /var/www/legal/application/modules/administracion/controllers/JuzgadoController.php(23): Application_Entity_Juzgado->insert()
#8 /var/www/legal/library/Zend/Controller/Action.php(516): Administracion_JuzgadoController->nuevoAction()
#9 /var/www/legal/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#10 /var/www/legal/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/legal/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/legal/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/legal/public/index.php(27): Zend_Application->run()
#14 {main}
2014-01-09T09:50:05-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Cannot add or update a child row: a foreign key constraint fails (`devlegal`.`juzgado`, CONSTRAINT `fk_juzgado_distrito_judicial1` FOREIGN KEY (`distrito_judicial_id`) REFERENCES `distrito_judicial` (`distrito_judicial_id`) ON DELETE NO ACTION ON UPDATE NO A)' in /var/www/legal/library/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /var/www/legal/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `ju...', Array)
#3 /var/www/legal/library/Zend/Db/Table/Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('juzgado', Array)
#4 /var/www/legal/library/Core/Db/Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#5 /var/www/legal/application/models/Juzgado.php(37): Core_Db_Table->insert(Array)
#6 /var/www/legal/application/entitys/Juzgado.php(45): Application_Model_Juzgado->insert(Array)
#7 /var/www/legal/application/modules/administracion/controllers/JuzgadoController.php(23): Application_Entity_Juzgado->insert()
#8 /var/www/legal/library/Zend/Controller/Action.php(516): Administracion_JuzgadoController->nuevoAction()
#9 /var/www/legal/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#10 /var/www/legal/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/legal/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/legal/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/legal/public/index.php(27): Zend_Application->run()
#14 {main}
2014-01-09T09:54:02-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Cannot add or update a child row: a foreign key constraint fails (`devlegal`.`juzgado`, CONSTRAINT `fk_juzgado_distrito_judicial1` FOREIGN KEY (`distrito_judicial_id`) REFERENCES `distrito_judicial` (`distrito_judicial_id`) ON DELETE NO ACTION ON UPDATE NO A)' in /var/www/legal/library/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /var/www/legal/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `ju...', Array)
#3 /var/www/legal/library/Zend/Db/Table/Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('juzgado', Array)
#4 /var/www/legal/library/Core/Db/Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#5 /var/www/legal/application/models/Juzgado.php(37): Core_Db_Table->insert(Array)
#6 /var/www/legal/application/entitys/Juzgado.php(45): Application_Model_Juzgado->insert(Array)
#7 /var/www/legal/application/modules/administracion/controllers/JuzgadoController.php(23): Application_Entity_Juzgado->insert()
#8 /var/www/legal/library/Zend/Controller/Action.php(516): Administracion_JuzgadoController->nuevoAction()
#9 /var/www/legal/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#10 /var/www/legal/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/legal/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/legal/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/legal/public/index.php(27): Zend_Application->run()
#14 {main}
2014-01-09T12:20:54-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Cannot add or update a child row: a foreign key constraint fails (`devlegal`.`juzgado`, CONSTRAINT `fk_juzgado_distrito_judicial1` FOREIGN KEY (`distrito_judicial_id`) REFERENCES `distrito_judicial` (`distrito_judicial_id`) ON DELETE NO ACTION ON UPDATE NO A)' in /var/www/legal/library/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /var/www/legal/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `ju...', Array)
#3 /var/www/legal/library/Zend/Db/Table/Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('juzgado', Array)
#4 /var/www/legal/library/Core/Db/Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#5 /var/www/legal/application/models/Juzgado.php(37): Core_Db_Table->insert(Array)
#6 /var/www/legal/application/entitys/Juzgado.php(45): Application_Model_Juzgado->insert(Array)
#7 /var/www/legal/application/modules/administracion/controllers/JuzgadoController.php(24): Application_Entity_Juzgado->insert()
#8 /var/www/legal/library/Zend/Controller/Action.php(516): Administracion_JuzgadoController->nuevoAction()
#9 /var/www/legal/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#10 /var/www/legal/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/legal/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/legal/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/legal/public/index.php(27): Zend_Application->run()
#14 {main}
<<<<<<< HEAD
<<<<<<< HEAD
2014-01-09T14:13:30-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Cannot add or update a child row: a foreign key constraint fails (`devlegal`.`implicado_caso`, CONSTRAINT `fk_implicado_expediente_implicado_parte1` FOREIGN KEY (`implicado_parte_id`) REFERENCES `implicado_parte` (`implicado_parte_id`) ON DELETE NO ACTION ON)' in /var/www/legal/library/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /var/www/legal/library/Zend/Db/Statement.php(323): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `im...', Array)
#3 /var/www/legal/library/Zend/Db/Table/Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('implicado_caso', Array)
#4 /var/www/legal/library/Core/Db/Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#5 /var/www/legal/application/models/Caso.php(45): Core_Db_Table->insert(Array)
#6 /var/www/legal/application/entitys/Caso.php(72): Application_Model_Caso->insert(Array, Array, Array)
#7 /var/www/legal/application/modules/abogado/controllers/CasoController.php(45): Application_Entity_Caso->insert(Object(Application_Entity_Implicado), Object(Application_Entity_ImplicadoCaso))
#8 /var/www/legal/library/Zend/Controller/Action.php(516): Abogado_CasoController->nuevoAction()
#9 /var/www/legal/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#10 /var/www/legal/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/legal/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/legal/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/legal/public/index.php(27): Zend_Application->run()
#14 {main}
=======
2014-01-09T16:10:44-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'dgamarra') AND (usuario_id <> 'dgamarra')
2014-01-09T16:11:14-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'dgamarra32') AND (usuario_id <> 'dgamarra32')
2014-01-09T16:11:14-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'dgamarra32') AND (usuario_id <> 'dgamarra32')
>>>>>>> 40b8bb6ce345e566050c120697cd034224f6385d
=======
2014-01-09T16:10:44-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'dgamarra') AND (usuario_id <> 'dgamarra')
2014-01-09T16:11:14-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'dgamarra32') AND (usuario_id <> 'dgamarra32')
2014-01-09T16:11:14-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'dgamarra32') AND (usuario_id <> 'dgamarra32')
>>>>>>> 00a93aa406f344ffc8675d033087060303d1fbf8
2014-01-10T10:37:31-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado') AND (usuario_id <> 'abogado')
2014-01-10T10:37:44-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado') AND (usuario_id <> 'abogado')
2014-01-10T10:38:02-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:38:03-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:38:04-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:38:04-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:38:04-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:38:04-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:38:04-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:38:42-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:38:44-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:38:46-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:38:53-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado') AND (usuario_id <> 'abogado')
2014-01-10T10:39:44-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado') AND (usuario_id <> 'abogado')
2014-01-10T10:39:46-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado') AND (usuario_id <> 'abogado')
2014-01-10T10:39:49-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:39:57-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:39:59-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:40:01-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:40:02-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:40:08-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:40:08-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:40:08-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:40:08-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:40:34-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:40:55-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:40:57-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:41:37-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:41:39-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:42:57-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:42:58-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:42:58-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:32-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:32-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:32-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:33-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:33-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:33-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:33-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:34-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:34-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:36-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:37-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:37-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:37-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:38-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:38-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:40-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:40-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:40-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:40-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:42-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:42-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:42-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:42-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:57-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:58-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:58-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:58-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:44:58-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:46:03-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:46:09-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:46:14-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:46:16-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:46:16-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:46:16-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:46:16-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:46:59-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:56:55-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:56:57-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T10:56:58-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T11:03:40-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T11:03:41-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T11:03:41-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T11:03:41-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T11:03:41-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T11:03:42-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T11:03:42-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T11:03:42-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T11:03:47-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T11:03:48-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T11:05:17-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T11:07:03-05:00 ERR (3): SELECT `usuario`.* FROM `usuario` WHERE (usuario_identity = 'abogado12') AND (usuario_id <> 'abogado12')
2014-01-10T15:19:23-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Cannot add or update a child row: a foreign key constraint fails (`devlegal`.`expediente`, CONSTRAINT `fk_expediente_caso1` FOREIGN KEY (`caso_id`) REFERENCES `caso` (`caso_id`) ON DELETE NO ACTION ON UPDATE NO ACTION)' in /var/www/legal/library/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /var/www/legal/library/Zend/Db/Statement.php(323): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `ex...', Array)
#3 /var/www/legal/library/Zend/Db/Table/Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('expediente', Array)
#4 /var/www/legal/library/Core/Db/Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#5 /var/www/legal/application/models/Expediente.php(37): Core_Db_Table->insert(Array)
#6 /var/www/legal/application/entitys/Expediente.php(55): Application_Model_Expediente->insert(Array)
#7 /var/www/legal/application/modules/abogado/controllers/ExpedienteController.php(38): Application_Entity_Expediente->insert()
#8 /var/www/legal/library/Zend/Controller/Action.php(516): Abogado_ExpedienteController->nuevoAction()
#9 /var/www/legal/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#10 /var/www/legal/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/legal/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/legal/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/legal/public/index.php(27): Zend_Application->run()
#14 {main}
2014-01-10T15:19:42-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Cannot add or update a child row: a foreign key constraint fails (`devlegal`.`expediente`, CONSTRAINT `fk_expediente_caso1` FOREIGN KEY (`caso_id`) REFERENCES `caso` (`caso_id`) ON DELETE NO ACTION ON UPDATE NO ACTION)' in /var/www/legal/library/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /var/www/legal/library/Zend/Db/Statement.php(323): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `ex...', Array)
#3 /var/www/legal/library/Zend/Db/Table/Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('expediente', Array)
#4 /var/www/legal/library/Core/Db/Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#5 /var/www/legal/application/models/Expediente.php(37): Core_Db_Table->insert(Array)
#6 /var/www/legal/application/entitys/Expediente.php(55): Application_Model_Expediente->insert(Array)
#7 /var/www/legal/application/modules/abogado/controllers/ExpedienteController.php(38): Application_Entity_Expediente->insert()
#8 /var/www/legal/library/Zend/Controller/Action.php(516): Abogado_ExpedienteController->nuevoAction()
#9 /var/www/legal/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#10 /var/www/legal/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/legal/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/legal/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/legal/public/index.php(27): Zend_Application->run()
#14 {main}
2014-01-10T15:20:28-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Cannot add or update a child row: a foreign key constraint fails (`devlegal`.`expediente`, CONSTRAINT `fk_expediente_caso1` FOREIGN KEY (`caso_id`) REFERENCES `caso` (`caso_id`) ON DELETE NO ACTION ON UPDATE NO ACTION)' in /var/www/legal/library/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /var/www/legal/library/Zend/Db/Statement.php(323): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `ex...', Array)
#3 /var/www/legal/library/Zend/Db/Table/Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('expediente', Array)
#4 /var/www/legal/library/Core/Db/Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#5 /var/www/legal/application/models/Expediente.php(37): Core_Db_Table->insert(Array)
#6 /var/www/legal/application/entitys/Expediente.php(55): Application_Model_Expediente->insert(Array)
#7 /var/www/legal/application/modules/abogado/controllers/ExpedienteController.php(38): Application_Entity_Expediente->insert()
#8 /var/www/legal/library/Zend/Controller/Action.php(516): Abogado_ExpedienteController->nuevoAction()
#9 /var/www/legal/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#10 /var/www/legal/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/legal/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/legal/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/legal/public/index.php(27): Zend_Application->run()
#14 {main}
2014-01-10T15:23:35-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Cannot add or update a child row: a foreign key constraint fails (`devlegal`.`expediente`, CONSTRAINT `fk_expediente_caso1` FOREIGN KEY (`caso_id`) REFERENCES `caso` (`caso_id`) ON DELETE NO ACTION ON UPDATE NO ACTION)' in /var/www/legal/library/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /var/www/legal/library/Zend/Db/Statement.php(323): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `ex...', Array)
#3 /var/www/legal/library/Zend/Db/Table/Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('expediente', Array)
#4 /var/www/legal/library/Core/Db/Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#5 /var/www/legal/application/models/Expediente.php(37): Core_Db_Table->insert(Array)
#6 /var/www/legal/application/entitys/Expediente.php(55): Application_Model_Expediente->insert(Array)
#7 /var/www/legal/application/modules/abogado/controllers/ExpedienteController.php(38): Application_Entity_Expediente->insert()
#8 /var/www/legal/library/Zend/Controller/Action.php(516): Abogado_ExpedienteController->nuevoAction()
#9 /var/www/legal/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#10 /var/www/legal/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/legal/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/legal/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/legal/public/index.php(27): Zend_Application->run()
#14 {main}
2014-01-10T17:02:58-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Cannot add or update a child row: a foreign key constraint fails (`devlegal`.`expediente`, CONSTRAINT `fk_expediente_caso1` FOREIGN KEY (`caso_id`) REFERENCES `caso` (`caso_id`) ON DELETE NO ACTION ON UPDATE NO ACTION)' in /var/www/legal/library/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /var/www/legal/library/Zend/Db/Statement.php(323): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `ex...', Array)
#3 /var/www/legal/library/Zend/Db/Table/Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('expediente', Array)
#4 /var/www/legal/library/Core/Db/Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#5 /var/www/legal/application/models/Expediente.php(37): Core_Db_Table->insert(Array)
#6 /var/www/legal/application/entitys/Expediente.php(58): Application_Model_Expediente->insert(Array)
#7 /var/www/legal/application/modules/abogado/controllers/ExpedienteController.php(41): Application_Entity_Expediente->insert()
#8 /var/www/legal/library/Zend/Controller/Action.php(516): Abogado_ExpedienteController->nuevoAction()
#9 /var/www/legal/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#10 /var/www/legal/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/legal/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/legal/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/legal/public/index.php(27): Zend_Application->run()
#14 {main}
2014-01-10T17:03:56-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Cannot add or update a child row: a foreign key constraint fails (`devlegal`.`expediente`, CONSTRAINT `fk_expediente_caso1` FOREIGN KEY (`caso_id`) REFERENCES `caso` (`caso_id`) ON DELETE NO ACTION ON UPDATE NO ACTION)' in /var/www/legal/library/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /var/www/legal/library/Zend/Db/Statement.php(323): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /var/www/legal/library/Zend/Db/Adapter/Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `ex...', Array)
#3 /var/www/legal/library/Zend/Db/Table/Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('expediente', Array)
#4 /var/www/legal/library/Core/Db/Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#5 /var/www/legal/application/models/Expediente.php(37): Core_Db_Table->insert(Array)
#6 /var/www/legal/application/entitys/Expediente.php(58): Application_Model_Expediente->insert(Array)
#7 /var/www/legal/application/modules/abogado/controllers/ExpedienteController.php(41): Application_Entity_Expediente->insert()
#8 /var/www/legal/library/Zend/Controller/Action.php(516): Abogado_ExpedienteController->nuevoAction()
#9 /var/www/legal/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#10 /var/www/legal/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/legal/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /var/www/legal/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/legal/public/index.php(27): Zend_Application->run()
#14 {main}
2014-01-12T06:40:22-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'usuario_empresa' in 'field list'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:77
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('INSERT INTO `us...')
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'INSERT INTO `us...')
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('INSERT INTO `us...')
#3 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `us...', Array)
#4 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('usuario', Array)
#5 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#6 C:\workspace\cemacc\application\models\Usuario.php(81): Core_Db_Table->insert(Array)
#7 C:\workspace\cemacc\application\entitys\Usuario.php(89): Application_Model_Usuario->insert(Array)
#8 C:\workspace\cemacc\application\modules\default\controllers\RegistroController.php(38): Application_Entity_Usuario->insert()
#9 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Default_RegistroController->indexAction()
#10 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#11 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#15 {main}
2014-01-12T06:44:17-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'usuario_empresa' in 'field list'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:77
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('INSERT INTO `us...')
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'INSERT INTO `us...')
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('INSERT INTO `us...')
#3 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `us...', Array)
#4 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('usuario', Array)
#5 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#6 C:\workspace\cemacc\application\models\Usuario.php(81): Core_Db_Table->insert(Array)
#7 C:\workspace\cemacc\application\entitys\Usuario.php(89): Application_Model_Usuario->insert(Array)
#8 C:\workspace\cemacc\application\modules\default\controllers\RegistroController.php(39): Application_Entity_Usuario->insert()
#9 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Default_RegistroController->indexAction()
#10 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#11 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#15 {main}
2014-01-12T06:47:27-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'usuario_empresa' in 'field list'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:77
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('INSERT INTO `us...')
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'INSERT INTO `us...')
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('INSERT INTO `us...')
#3 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `us...', Array)
#4 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('usuario', Array)
#5 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#6 C:\workspace\cemacc\application\models\Usuario.php(81): Core_Db_Table->insert(Array)
#7 C:\workspace\cemacc\application\entitys\Usuario.php(89): Application_Model_Usuario->insert(Array)
#8 C:\workspace\cemacc\application\modules\default\controllers\RegistroController.php(39): Application_Entity_Usuario->insert()
#9 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Default_RegistroController->indexAction()
#10 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#11 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#15 {main}
2014-01-12T06:52:59-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'usuario_empresa' in 'field list'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:77
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('INSERT INTO `us...')
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'INSERT INTO `us...')
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('INSERT INTO `us...')
#3 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `us...', Array)
#4 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('usuario', Array)
#5 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#6 C:\workspace\cemacc\application\models\Usuario.php(81): Core_Db_Table->insert(Array)
#7 C:\workspace\cemacc\application\entitys\Usuario.php(89): Application_Model_Usuario->insert(Array)
#8 C:\workspace\cemacc\application\modules\default\controllers\RegistroController.php(46): Application_Entity_Usuario->insert()
#9 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Default_RegistroController->indexAction()
#10 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#11 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#15 {main}
2014-01-12T06:53:23-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'usuario_empresa' in 'field list'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:77
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('INSERT INTO `us...')
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'INSERT INTO `us...')
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('INSERT INTO `us...')
#3 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `us...', Array)
#4 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('usuario', Array)
#5 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#6 C:\workspace\cemacc\application\models\Usuario.php(81): Core_Db_Table->insert(Array)
#7 C:\workspace\cemacc\application\entitys\Usuario.php(89): Application_Model_Usuario->insert(Array)
#8 C:\workspace\cemacc\application\modules\default\controllers\RegistroController.php(46): Application_Entity_Usuario->insert()
#9 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Default_RegistroController->indexAction()
#10 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#11 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#15 {main}
2014-01-12T06:56:45-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'usuario_empresa' in 'field list'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:77
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('INSERT INTO `us...')
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'INSERT INTO `us...')
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('INSERT INTO `us...')
#3 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `us...', Array)
#4 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('usuario', Array)
#5 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#6 C:\workspace\cemacc\application\models\Usuario.php(81): Core_Db_Table->insert(Array)
#7 C:\workspace\cemacc\application\entitys\Usuario.php(99): Application_Model_Usuario->insert(Array)
#8 C:\workspace\cemacc\application\modules\default\controllers\RegistroController.php(47): Application_Entity_Usuario->insert()
#9 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Default_RegistroController->indexAction()
#10 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#11 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#15 {main}
2014-01-12T06:57:21-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'usuario_empresa' in 'field list'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:77
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('INSERT INTO `us...')
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'INSERT INTO `us...')
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('INSERT INTO `us...')
#3 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `us...', Array)
#4 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('usuario', Array)
#5 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#6 C:\workspace\cemacc\application\models\Usuario.php(81): Core_Db_Table->insert(Array)
#7 C:\workspace\cemacc\application\entitys\Usuario.php(99): Application_Model_Usuario->insert(Array)
#8 C:\workspace\cemacc\application\modules\default\controllers\RegistroController.php(47): Application_Entity_Usuario->insert()
#9 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Default_RegistroController->indexAction()
#10 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#11 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#15 {main}
2014-01-12T07:03:53-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'usuario_empresa' in 'field list'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:77
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('INSERT INTO `us...')
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'INSERT INTO `us...')
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('INSERT INTO `us...')
#3 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `us...', Array)
#4 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('usuario', Array)
#5 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#6 C:\workspace\cemacc\application\models\Usuario.php(81): Core_Db_Table->insert(Array)
#7 C:\workspace\cemacc\application\entitys\Usuario.php(99): Application_Model_Usuario->insert(Array)
#8 C:\workspace\cemacc\application\modules\default\controllers\RegistroController.php(47): Application_Entity_Usuario->insert()
#9 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Default_RegistroController->indexAction()
#10 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#11 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#15 {main}
2014-01-12T07:05:50-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'usuario_empresa' in 'field list'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:77
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('INSERT INTO `us...')
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'INSERT INTO `us...')
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('INSERT INTO `us...')
#3 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `us...', Array)
#4 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('usuario', Array)
#5 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#6 C:\workspace\cemacc\application\models\Usuario.php(81): Core_Db_Table->insert(Array)
#7 C:\workspace\cemacc\application\entitys\Usuario.php(99): Application_Model_Usuario->insert(Array)
#8 C:\workspace\cemacc\application\modules\default\controllers\RegistroController.php(47): Application_Entity_Usuario->insert()
#9 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Default_RegistroController->indexAction()
#10 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#11 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#15 {main}
2014-01-12T07:06:45-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'usuario_empresa' in 'field list'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:77
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('INSERT INTO `us...')
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'INSERT INTO `us...')
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('INSERT INTO `us...')
#3 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `us...', Array)
#4 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('usuario', Array)
#5 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#6 C:\workspace\cemacc\application\models\Usuario.php(81): Core_Db_Table->insert(Array)
#7 C:\workspace\cemacc\application\entitys\Usuario.php(99): Application_Model_Usuario->insert(Array)
#8 C:\workspace\cemacc\application\modules\default\controllers\RegistroController.php(47): Application_Entity_Usuario->insert()
#9 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Default_RegistroController->indexAction()
#10 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#11 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#15 {main}
2014-01-26T21:49:20-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Duplicate entry '1' for key 'PRIMARY'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:214
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(323): Zend_Db_Statement_Mysqli->_execute(Array)
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `ad...', Array)
#3 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('adquisicion_det...', Array)
#4 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#5 C:\workspace\cemacc\application\models\AdquisicionDetalle.php(37): Core_Db_Table->insert(Array)
#6 C:\workspace\cemacc\application\entitys\AdquisicionDetalle.php(45): Application_Model_AdquisicionDetalle->insert(Array)
#7 C:\workspace\cemacc\application\modules\logistica\controllers\AdquisicionController.php(37): Application_Entity_AdquisicionDetalle->insert()
#8 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Logistica_AdquisicionController->nuevoAction()
#9 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#10 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#14 {main}
2014-01-26T21:49:20-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Duplicate entry '2' for key 'PRIMARY'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:214
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(323): Zend_Db_Statement_Mysqli->_execute(Array)
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `ad...', Array)
#3 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('adquisicion_det...', Array)
#4 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#5 C:\workspace\cemacc\application\models\AdquisicionDetalle.php(37): Core_Db_Table->insert(Array)
#6 C:\workspace\cemacc\application\entitys\AdquisicionDetalle.php(45): Application_Model_AdquisicionDetalle->insert(Array)
#7 C:\workspace\cemacc\application\modules\logistica\controllers\AdquisicionController.php(37): Application_Entity_AdquisicionDetalle->insert()
#8 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Logistica_AdquisicionController->nuevoAction()
#9 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#10 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#14 {main}
2014-01-26T21:49:20-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Duplicate entry '3' for key 'PRIMARY'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:214
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(323): Zend_Db_Statement_Mysqli->_execute(Array)
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `ad...', Array)
#3 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('adquisicion_det...', Array)
#4 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#5 C:\workspace\cemacc\application\models\AdquisicionDetalle.php(37): Core_Db_Table->insert(Array)
#6 C:\workspace\cemacc\application\entitys\AdquisicionDetalle.php(45): Application_Model_AdquisicionDetalle->insert(Array)
#7 C:\workspace\cemacc\application\modules\logistica\controllers\AdquisicionController.php(37): Application_Entity_AdquisicionDetalle->insert()
#8 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Logistica_AdquisicionController->nuevoAction()
#9 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#10 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#14 {main}
2014-01-26T22:04:22-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Duplicate entry '1' for key 'PRIMARY'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:214
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(323): Zend_Db_Statement_Mysqli->_execute(Array)
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `ad...', Array)
#3 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('adquisicion_det...', Array)
#4 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#5 C:\workspace\cemacc\application\models\AdquisicionDetalle.php(37): Core_Db_Table->insert(Array)
#6 C:\workspace\cemacc\application\entitys\AdquisicionDetalle.php(45): Application_Model_AdquisicionDetalle->insert(Array)
#7 C:\workspace\cemacc\application\modules\logistica\controllers\AdquisicionController.php(36): Application_Entity_AdquisicionDetalle->insert()
#8 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Logistica_AdquisicionController->nuevoAction()
#9 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#10 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#14 {main}
2014-01-26T22:07:12-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Duplicate entry '1' for key 'PRIMARY'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:214
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(323): Zend_Db_Statement_Mysqli->_execute(Array)
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `ad...', Array)
#3 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('adquisicion_det...', Array)
#4 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#5 C:\workspace\cemacc\application\models\AdquisicionDetalle.php(37): Core_Db_Table->insert(Array)
#6 C:\workspace\cemacc\application\entitys\AdquisicionDetalle.php(45): Application_Model_AdquisicionDetalle->insert(Array)
#7 C:\workspace\cemacc\application\modules\logistica\controllers\AdquisicionController.php(35): Application_Entity_AdquisicionDetalle->insert()
#8 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Logistica_AdquisicionController->nuevoAction()
#9 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#10 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#14 {main}
2014-01-26T22:15:48-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Duplicate entry '1' for key 'PRIMARY'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:214
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(323): Zend_Db_Statement_Mysqli->_execute(Array)
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `ad...', Array)
#3 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('adquisicion_det...', Array)
#4 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#5 C:\workspace\cemacc\application\models\AdquisicionDetalle.php(37): Core_Db_Table->insert(Array)
#6 C:\workspace\cemacc\application\entitys\AdquisicionDetalle.php(45): Application_Model_AdquisicionDetalle->insert(Array)
#7 C:\workspace\cemacc\application\modules\logistica\controllers\AdquisicionController.php(38): Application_Entity_AdquisicionDetalle->insert()
#8 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Logistica_AdquisicionController->nuevoAction()
#9 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#10 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#14 {main}
2014-03-14T02:30:57-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'paquete_nombre' in 'field list'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:77
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('INSERT INTO `ad...')
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'INSERT INTO `ad...')
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('INSERT INTO `ad...')
#3 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `ad...', Array)
#4 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('adquisicion', Array)
#5 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#6 C:\workspace\cemacc\application\models\Adquisicion.php(51): Core_Db_Table->insert(Array)
#7 C:\workspace\cemacc\application\entitys\Paquete.php(42): Application_Model_Adquisicion->insert(Array)
#8 C:\workspace\cemacc\application\modules\administracion\controllers\PaqueteController.php(29): Application_Entity_Paquete->insert()
#9 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Administracion_PaqueteController->nuevoAction()
#10 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#11 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#15 {main}
2014-03-14T02:33:10-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'paquete_nombre' in 'field list'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:77
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('INSERT INTO `pu...')
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'INSERT INTO `pu...')
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('INSERT INTO `pu...')
#3 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `pu...', Array)
#4 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('publicacion', Array)
#5 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#6 C:\workspace\cemacc\application\models\Paquete.php(67): Core_Db_Table->insert(Array)
#7 C:\workspace\cemacc\application\entitys\Paquete.php(42): Application_Model_Paquete->insert(Array)
#8 C:\workspace\cemacc\application\modules\administracion\controllers\PaqueteController.php(29): Application_Entity_Paquete->insert()
#9 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Administracion_PaqueteController->nuevoAction()
#10 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#11 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#15 {main}
2014-03-14T20:32:30-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Subquery returns more than 1 row' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:214
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(323): Zend_Db_Statement_Mysqli->_execute(Array)
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `pu...', Array)
#3 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('publicacion', Array)
#4 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#5 C:\workspace\cemacc\application\models\Publicacion.php(67): Core_Db_Table->insert(Array)
#6 C:\workspace\cemacc\application\entitys\Publicacion.php(73): Application_Model_Publicacion->insert(Array)
#7 C:\workspace\cemacc\application\modules\ventas\controllers\PublicarController.php(67): Application_Entity_Publicacion->insert()
#8 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Ventas_PublicarController->nuevoAction()
#9 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#10 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#14 {main}
2014-03-14T20:33:04-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Subquery returns more than 1 row' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:214
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(323): Zend_Db_Statement_Mysqli->_execute(Array)
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `pu...', Array)
#3 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('publicacion', Array)
#4 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#5 C:\workspace\cemacc\application\models\Publicacion.php(67): Core_Db_Table->insert(Array)
#6 C:\workspace\cemacc\application\entitys\Publicacion.php(73): Application_Model_Publicacion->insert(Array)
#7 C:\workspace\cemacc\application\modules\ventas\controllers\PublicarController.php(67): Application_Entity_Publicacion->insert()
#8 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Ventas_PublicarController->nuevoAction()
#9 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#10 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#14 {main}
2014-03-23T10:59:28-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Duplicate entry '12' for key 'PRIMARY'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:214
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(323): Zend_Db_Statement_Mysqli->_execute(Array)
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `ub...', Array)
#3 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('ubicacion', Array)
#4 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#5 C:\workspace\cemacc\application\models\Ubicacion.php(37): Core_Db_Table->insert(Array)
#6 C:\workspace\cemacc\application\entitys\Ubicacion.php(42): Application_Model_Ubicacion->insert(Array)
#7 C:\workspace\cemacc\application\modules\administracion\controllers\EmpresaController.php(37): Application_Entity_Ubicacion->insert()
#8 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Administracion_EmpresaController->nuevoAction()
#9 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#10 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#14 {main}
2014-03-23T11:00:15-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Duplicate entry '13' for key 'PRIMARY'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:214
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(323): Zend_Db_Statement_Mysqli->_execute(Array)
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `ub...', Array)
#3 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('ubicacion', Array)
#4 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#5 C:\workspace\cemacc\application\models\Ubicacion.php(37): Core_Db_Table->insert(Array)
#6 C:\workspace\cemacc\application\entitys\Ubicacion.php(42): Application_Model_Ubicacion->insert(Array)
#7 C:\workspace\cemacc\application\modules\administracion\controllers\EmpresaController.php(37): Application_Entity_Ubicacion->insert()
#8 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Administracion_EmpresaController->nuevoAction()
#9 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#10 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#14 {main}
2014-03-23T11:00:51-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Duplicate entry '14' for key 'PRIMARY'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:214
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(323): Zend_Db_Statement_Mysqli->_execute(Array)
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `ub...', Array)
#3 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('ubicacion', Array)
#4 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#5 C:\workspace\cemacc\application\models\Ubicacion.php(37): Core_Db_Table->insert(Array)
#6 C:\workspace\cemacc\application\entitys\Ubicacion.php(42): Application_Model_Ubicacion->insert(Array)
#7 C:\workspace\cemacc\application\modules\administracion\controllers\EmpresaController.php(38): Application_Entity_Ubicacion->insert()
#8 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Administracion_EmpresaController->nuevoAction()
#9 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#10 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#14 {main}
2014-03-23T11:01:46-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Duplicate entry '15' for key 'PRIMARY'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:214
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(323): Zend_Db_Statement_Mysqli->_execute(Array)
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `ub...', Array)
#3 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('ubicacion', Array)
#4 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#5 C:\workspace\cemacc\application\models\Ubicacion.php(37): Core_Db_Table->insert(Array)
#6 C:\workspace\cemacc\application\entitys\Ubicacion.php(42): Application_Model_Ubicacion->insert(Array)
#7 C:\workspace\cemacc\application\modules\administracion\controllers\EmpresaController.php(38): Application_Entity_Ubicacion->insert()
#8 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Administracion_EmpresaController->nuevoAction()
#9 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#10 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#14 {main}
2014-07-06T17:22:10-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'trainer_nombre' in 'field list'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:77
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('INSERT INTO `tr...')
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'INSERT INTO `tr...')
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('INSERT INTO `tr...')
#3 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `tr...', Array)
#4 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('trainer', Array)
#5 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#6 C:\workspace\cemacc\application\models\Trainer.php(29): Core_Db_Table->insert(Array)
#7 C:\workspace\cemacc\application\entitys\Trainer.php(42): Application_Model_Trainer->insert(Array)
#8 C:\workspace\cemacc\application\modules\administracion\controllers\TrainerController.php(44): Application_Entity_Trainer->insert()
#9 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Administracion_TrainerController->nuevoAction()
#10 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#11 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#15 {main}
2014-07-06T17:23:17-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'trainer_nombre' in 'field list'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:77
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('INSERT INTO `tr...')
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'INSERT INTO `tr...')
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('INSERT INTO `tr...')
#3 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `tr...', Array)
#4 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('trainer', Array)
#5 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#6 C:\workspace\cemacc\application\models\Trainer.php(29): Core_Db_Table->insert(Array)
#7 C:\workspace\cemacc\application\entitys\Trainer.php(42): Application_Model_Trainer->insert(Array)
#8 C:\workspace\cemacc\application\modules\administracion\controllers\TrainerController.php(44): Application_Entity_Trainer->insert()
#9 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Administracion_TrainerController->nuevoAction()
#10 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#11 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#15 {main}
2014-07-06T17:27:06-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'trainer_nombre' in 'field list'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:77
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('INSERT INTO `tr...')
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'INSERT INTO `tr...')
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('INSERT INTO `tr...')
#3 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `tr...', Array)
#4 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('trainer', Array)
#5 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#6 C:\workspace\cemacc\application\models\Trainer.php(29): Core_Db_Table->insert(Array)
#7 C:\workspace\cemacc\application\entitys\Trainer.php(42): Application_Model_Trainer->insert(Array)
#8 C:\workspace\cemacc\application\modules\administracion\controllers\TrainerController.php(43): Application_Entity_Trainer->insert()
#9 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Administracion_TrainerController->nuevoAction()
#10 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#11 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#15 {main}
2014-07-06T17:37:57-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'trainer_nombre' in 'field list'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:77
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('INSERT INTO `tr...')
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'INSERT INTO `tr...')
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('INSERT INTO `tr...')
#3 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `tr...', Array)
#4 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('trainer', Array)
#5 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#6 C:\workspace\cemacc\application\models\Trainer.php(29): Core_Db_Table->insert(Array)
#7 C:\workspace\cemacc\application\entitys\Trainer.php(42): Application_Model_Trainer->insert(Array)
#8 C:\workspace\cemacc\application\modules\administracion\controllers\TrainerController.php(43): Application_Entity_Trainer->insert()
#9 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Administracion_TrainerController->nuevoAction()
#10 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#11 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#15 {main}
2014-07-06T17:38:07-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'trainer_nombre' in 'field list'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:77
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('INSERT INTO `tr...')
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'INSERT INTO `tr...')
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('INSERT INTO `tr...')
#3 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `tr...', Array)
#4 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('trainer', Array)
#5 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#6 C:\workspace\cemacc\application\models\Trainer.php(29): Core_Db_Table->insert(Array)
#7 C:\workspace\cemacc\application\entitys\Trainer.php(42): Application_Model_Trainer->insert(Array)
#8 C:\workspace\cemacc\application\modules\administracion\controllers\TrainerController.php(43): Application_Entity_Trainer->insert()
#9 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Administracion_TrainerController->nuevoAction()
#10 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#11 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#15 {main}
2014-07-06T17:38:28-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'trainer_nombre' in 'field list'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:77
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('INSERT INTO `tr...')
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'INSERT INTO `tr...')
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('INSERT INTO `tr...')
#3 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `tr...', Array)
#4 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('trainer', Array)
#5 C:\workspace\cemacc\library\Core\Db\Table.php(16): Zend_Db_Table_Abstract->insert(Array)
#6 C:\workspace\cemacc\application\models\Trainer.php(29): Core_Db_Table->insert(Array)
#7 C:\workspace\cemacc\application\entitys\Trainer.php(42): Application_Model_Trainer->insert(Array)
#8 C:\workspace\cemacc\application\modules\administracion\controllers\TrainerController.php(43): Application_Entity_Trainer->insert()
#9 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Administracion_TrainerController->nuevoAction()
#10 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('nuevoAction')
#11 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#15 {main}
2014-07-22T21:31:05-05:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'asesoria_id' in 'field list'' in C:\workspace\cemacc\library\Zend\Db\Statement\Mysqli.php:77
Stack trace:
#0 C:\workspace\cemacc\library\Zend\Db\Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('UPDATE `adquisi...')
#1 C:\workspace\cemacc\library\Zend\Db\Adapter\Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'UPDATE `adquisi...')
#2 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('UPDATE `adquisi...')
#3 C:\workspace\cemacc\library\Zend\Db\Adapter\Abstract.php(635): Zend_Db_Adapter_Abstract->query('UPDATE `adquisi...', Array)
#4 C:\workspace\cemacc\library\Zend\Db\Table\Abstract.php(1133): Zend_Db_Adapter_Abstract->update('adquisicion', Array, 'adquisicion_id ...')
#5 C:\workspace\cemacc\library\Core\Db\Table.php(20): Zend_Db_Table_Abstract->update(Array, 'adquisicion_id ...')
#6 C:\workspace\cemacc\application\models\Asesoria.php(72): Core_Db_Table->update(Array, 'adquisicion_id ...')
#7 C:\workspace\cemacc\application\entitys\Asesoria.php(51): Application_Model_Asesoria->update('1', Array)
#8 C:\workspace\cemacc\application\modules\administracion\controllers\AsesoriaController.php(51): Application_Entity_Asesoria->update()
#9 C:\workspace\cemacc\library\Zend\Controller\Action.php(516): Administracion_AsesoriaController->editarAction()
#10 C:\workspace\cemacc\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('editarAction')
#11 C:\workspace\cemacc\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 C:\workspace\cemacc\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#13 C:\workspace\cemacc\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 C:\workspace\cemacc\public\index.php(27): Zend_Application->run()
#15 {main}
